--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with PolyORB_HI.Periodic_Task;
pragma Elaborate_All (PolyORB_HI.Periodic_Task);

package PolyORB_HI_Generated.Job is

  --  Periodic task : video_captor_t

  procedure surveillance_system_video_captor_t_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_video_captor_t_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.video_video_captor_t_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (5000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (5000),
      Task_Priority => 13,
      Task_Stack_Size => 100000,
      Job => surveillance_system_video_captor_t_Job);

  --  Periodic task : video_sender_t

  procedure surveillance_system_video_sender_t_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_video_sender_t_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.video_video_sender_t_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (5000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (5000),
      Task_Priority => 10,
      Task_Stack_Size => 100000,
      Job => surveillance_system_video_sender_t_Job);

end PolyORB_HI_Generated.Job;
