--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with Interfaces;
with PolyORB_HI.Port_Type_Marshallers;
with PolyORB_HI.Utils;
with PolyORB_HI_Generated.Activity;
use PolyORB_HI_Generated.Activity;
with PolyORB_HI_Generated.Marshallers;

package body PolyORB_HI_Generated.Transport is

  procedure surveillance_system_video_captor_t_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure surveillance_system_video_sender_t_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  -------------
  -- Deliver -- 
  -------------

  procedure Deliver
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : PolyORB_HI.Messages.Message_Type;
    Value : Interfaces.Unsigned_16;
    Port : PolyORB_HI_Generated.Deployment.Port_Type;
    use type PolyORB_HI.Streams.Stream_Element_Offset;
  begin
    PolyORB_HI.Messages.Write
     (Msg,
      Message
       ((Message'First
          + PolyORB_HI.Messages.Header_Size) .. Message'Last));
    PolyORB_HI.Port_Type_Marshallers.Unmarshall
     (Value,
      Msg);
    Port :=
     PolyORB_HI.Utils.Corresponding_Port
       (Value);
    if (Entity
      = PolyORB_HI_Generated.Deployment.video_video_captor_t_K)
    then
      surveillance_system_video_captor_t_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.video_video_sender_t_K)
    then
      surveillance_system_video_sender_t_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    end if;
  end Deliver;

  function surveillance_system_video_captor_t_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  ----------
  -- Send -- 
  ----------

  function Send
   (From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Messages.Message_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : constant PolyORB_HI.Streams.Stream_Element_Array :=
     PolyORB_HI.Messages.Encapsulate
       (Message,
        From,
        Entity);
  begin
    if (From
      = PolyORB_HI_Generated.Deployment.video_video_captor_t_K)
    then
      return surveillance_system_video_captor_t_Send
       (Entity,
        Msg);
    else
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_Transport);
    end if;
  end Send;

  ------------------------------------------------
  -- surveillance_system_video_captor_t_Deliver -- 
  ------------------------------------------------

  procedure surveillance_system_video_captor_t_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_video_captor_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.video_video_captor_t_camera1_capture_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (camera1_capture,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.video_video_captor_t_K,
        Thread_Interface_Ü,
        From);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.video_video_captor_t_camera2_capture_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (camera2_capture,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.video_video_captor_t_K,
        Thread_Interface_Ü,
        From);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.video_video_captor_t_camera3_capture_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (camera3_capture,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.video_video_captor_t_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_video_captor_t_Deliver;

  ---------------------------------------------
  -- surveillance_system_video_captor_t_Send -- 
  ---------------------------------------------

  function surveillance_system_video_captor_t_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
    use PolyORB_HI_Generated.Deployment;
  begin
    if (Entity
      = PolyORB_HI_Generated.Deployment.video_video_sender_t_K)
    then
      Deliver
       (Entity,
        Message);
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_None);
    else
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_Transport);
    end if;
  end surveillance_system_video_captor_t_Send;

  ------------------------------------------------
  -- surveillance_system_video_sender_t_Deliver -- 
  ------------------------------------------------

  procedure surveillance_system_video_sender_t_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_video_sender_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.video_video_sender_t_message_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (message,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.video_video_sender_t_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_video_sender_t_Deliver;

end PolyORB_HI_Generated.Transport;
