--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package body PolyORB_HI_Generated.Subprograms is

  -----------------------------------------
  -- event_handlers_video_captor_handler -- 
  -----------------------------------------

  procedure event_handlers_video_captor_handler is
    Nyi : exception;
  begin
    raise Nyi;
  end event_handlers_video_captor_handler;

  -----------------------------------------
  -- event_handlers_video_sender_handler -- 
  -----------------------------------------

  procedure event_handlers_video_sender_handler is
    Nyi : exception;
  begin
    raise Nyi;
  end event_handlers_video_sender_handler;

end PolyORB_HI_Generated.Subprograms;
