--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Subprograms is

  procedure event_handlers_video_captor_handler;

  procedure event_handlers_video_sender_handler;

end PolyORB_HI_Generated.Subprograms;
