--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type camera_image is
   new Standard.Integer;

  --  camera_image'Object_Size ~= 32 bits

  camera_image_Default_Value : constant camera_image :=
   0;

  type captor_data is
   new Standard.Integer;

  --  captor_data'Object_Size ~= 32 bits

  captor_data_Default_Value : constant captor_data :=
   0;

end PolyORB_HI_Generated.Types;
