--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with Interfaces;
with PolyORB_HI.Port_Type_Marshallers;
with PolyORB_HI.Utils;
with PolyORB_HI_Generated.Activity;
use PolyORB_HI_Generated.Activity;
with PolyORB_HI_Generated.Marshallers;

package body PolyORB_HI_Generated.Transport is

  procedure surveillance_system_detector1_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure surveillance_system_detector2_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure surveillance_system_detector3_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure surveillance_system_rfid_reader_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  -------------
  -- Deliver -- 
  -------------

  procedure Deliver
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : PolyORB_HI.Messages.Message_Type;
    Value : Interfaces.Unsigned_16;
    Port : PolyORB_HI_Generated.Deployment.Port_Type;
    use type PolyORB_HI.Streams.Stream_Element_Offset;
  begin
    PolyORB_HI.Messages.Write
     (Msg,
      Message
       ((Message'First
          + PolyORB_HI.Messages.Header_Size) .. Message'Last));
    PolyORB_HI.Port_Type_Marshallers.Unmarshall
     (Value,
      Msg);
    Port :=
     PolyORB_HI.Utils.Corresponding_Port
       (Value);
    if (Entity
      = PolyORB_HI_Generated.Deployment.main_detector1_K)
    then
      surveillance_system_detector1_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.main_detector2_K)
    then
      surveillance_system_detector2_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.main_detector3_K)
    then
      surveillance_system_detector3_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.main_rfid_reader_K)
    then
      surveillance_system_rfid_reader_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    end if;
  end Deliver;

  function surveillance_system_alarm_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  function surveillance_system_rfid_reader_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  ----------
  -- Send -- 
  ----------

  function Send
   (From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Messages.Message_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : constant PolyORB_HI.Streams.Stream_Element_Array :=
     PolyORB_HI.Messages.Encapsulate
       (Message,
        From,
        Entity);
  begin
    if (From
      = PolyORB_HI_Generated.Deployment.main_alarm_K)
    then
      return surveillance_system_alarm_Send
       (Entity,
        Msg);
    elsif (From
      = PolyORB_HI_Generated.Deployment.main_rfid_reader_K)
    then
      return surveillance_system_rfid_reader_Send
       (Entity,
        Msg);
    else
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_Transport);
    end if;
  end Send;

  ------------------------------------
  -- surveillance_system_alarm_Send -- 
  ------------------------------------

  function surveillance_system_alarm_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
  begin
    --  Device
    --  Device
    --  Device
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end surveillance_system_alarm_Send;

  -------------------------------------------
  -- surveillance_system_detector1_Deliver -- 
  -------------------------------------------

  procedure surveillance_system_detector1_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_detector_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.main_detector1_motion_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (motion,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector1_K,
        Thread_Interface_Ü,
        From);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.main_detector1_door_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (door,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector1_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_detector1_Deliver;

  -------------------------------------------
  -- surveillance_system_detector2_Deliver -- 
  -------------------------------------------

  procedure surveillance_system_detector2_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_detector_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.main_detector2_motion_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (motion,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector2_K,
        Thread_Interface_Ü,
        From);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.main_detector2_door_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (door,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector2_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_detector2_Deliver;

  -------------------------------------------
  -- surveillance_system_detector3_Deliver -- 
  -------------------------------------------

  procedure surveillance_system_detector3_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_detector_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.main_detector3_motion_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (motion,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector3_K,
        Thread_Interface_Ü,
        From);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.main_detector3_door_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (door,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_detector3_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_detector3_Deliver;

  ---------------------------------------------
  -- surveillance_system_rfid_reader_Deliver -- 
  ---------------------------------------------

  procedure surveillance_system_rfid_reader_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : surveillance_system_rfid_thread_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.main_rfid_reader_rfid_read_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (rfid_read,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_K,
        Thread_Interface_Ü,
        From);
    end if;
  end surveillance_system_rfid_reader_Deliver;

  ------------------------------------------
  -- surveillance_system_rfid_reader_Send -- 
  ------------------------------------------

  function surveillance_system_rfid_reader_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
  begin
    --  Device
    --  Device
    --  Device
    --  Device
    --  Device
    --  Device
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end surveillance_system_rfid_reader_Send;

end PolyORB_HI_Generated.Transport;
