--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Port_Kinds;
with System;
with PolyORB_HI_Generated.Marshallers;
with PolyORB_HI_Generated.Transport;
with PolyORB_HI.Thread_Interrogators;
pragma Elaborate_All (PolyORB_HI.Thread_Interrogators);
with PolyORB_HI_Generated.Subprograms;

package body PolyORB_HI_Generated.Activity is

  --  BEGIN: Data types used by all instances of component 
  --  alarm_activator.impl

  type surveillance_system_alarm_activator_impl_Integer_Array is
   array (surveillance_system_alarm_activator_impl_Port_Type)
     of Standard.Integer;

  type surveillance_system_alarm_activator_impl_Port_Kind_Array is
   array (surveillance_system_alarm_activator_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Main_1_Max_Port_Image_Size is
   Integer range 1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size;

  subtype UT_Activity_Main_surveillance_system_alarm_activator_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Main_1_Max_Port_Image_Size);

  type surveillance_system_alarm_activator_impl_Port_Image_Array is
   array (surveillance_system_alarm_activator_impl_Port_Type)
     of UT_Activity_Main_surveillance_system_alarm_activator_impl_Port_Image_Array_Component;

  type surveillance_system_alarm_activator_impl_Address_Array is
   array (surveillance_system_alarm_activator_impl_Port_Type)
     of System.Address;

  type surveillance_system_alarm_activator_impl_Overflow_Protocol_Array is
   array (surveillance_system_alarm_activator_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component alarm_activator.impl

  surveillance_system_alarm_Port_Kinds : constant surveillance_system_alarm_activator_impl_Port_Kind_Array :=
   (detected =>
     PolyORB_HI.Port_Kinds.Out_Event_Port,
    test =>
     PolyORB_HI.Port_Kinds.In_Event_Data_Port);

  surveillance_system_alarm_Port_Images : constant surveillance_system_alarm_activator_impl_Port_Image_Array :=
   (detected =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_alarm_detected_K),
    test =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_alarm_test_K));

  surveillance_system_alarm_FIFO_Sizes : constant surveillance_system_alarm_activator_impl_Integer_Array :=
   (detected =>
     -1,
    test =>
     16);

  surveillance_system_alarm_Offsets : constant surveillance_system_alarm_activator_impl_Integer_Array :=
   (detected =>
     0,
    test =>
     1);

  surveillance_system_alarm_Overflow_Protocols : constant surveillance_system_alarm_activator_impl_Overflow_Protocol_Array :=
   (detected =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    test =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  surveillance_system_alarm_Urgencies : constant surveillance_system_alarm_activator_impl_Integer_Array :=
   (detected =>
     0,
    test =>
     0);

  surveillance_system_alarm_Total_FIFO_Size : constant Standard.Integer :=
   16;

  surveillance_system_alarm_N_Destinations : constant surveillance_system_alarm_activator_impl_Integer_Array :=
   (detected =>
     0,
    test =>
     0);

  alarm_Destinations : constant surveillance_system_alarm_activator_impl_Address_Array :=
   (detected =>
     System.null_Address,
    test =>
     System.null_Address);

  package surveillance_system_alarm_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => surveillance_system_alarm_activator_impl_Port_Type,
      Integer_Array => surveillance_system_alarm_activator_impl_Integer_Array,
      Port_Kind_Array => surveillance_system_alarm_activator_impl_Port_Kind_Array,
      Port_Image_Array => surveillance_system_alarm_activator_impl_Port_Image_Array,
      Address_Array => surveillance_system_alarm_activator_impl_Address_Array,
      Overflow_Protocol_Array => surveillance_system_alarm_activator_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => surveillance_system_alarm_activator_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.main_alarm_K,
      Thread_Port_Kinds => surveillance_system_alarm_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => surveillance_system_alarm_Port_Images,
      Thread_Fifo_Sizes => surveillance_system_alarm_FIFO_Sizes,
      Thread_Fifo_Offsets => surveillance_system_alarm_Offsets,
      Thread_Overflow_Protocols => surveillance_system_alarm_Overflow_Protocols,
      Urgencies => surveillance_system_alarm_Urgencies,
      Global_Data_Queue_Size => surveillance_system_alarm_Total_FIFO_Size,
      N_Destinations => surveillance_system_alarm_N_Destinations,
      Destinations => alarm_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => surveillance_system_alarm_Task.Next_Deadline);

  --  Periodic task : alarm

  -----------------------------------
  -- surveillance_system_alarm_Job -- 
  -----------------------------------

  function surveillance_system_alarm_Job return PolyORB_HI.Errors.Error_Kind is
    test_V : PolyORB_HI_Generated.Types.Integer_Type;
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    if (surveillance_system_alarm_Interrogators.Get_Count
     (test)
      /= -1)
    then
      test_V :=
       surveillance_system_alarm_Interrogators.Get_Value
         (test).test_DATA;
    else
      test_V :=
       PolyORB_HI_Generated.Types.Integer_Type_Default_Value;
    end if;
    --  Dequeue the IN port values
    surveillance_system_alarm_Interrogators.Next_Value
     (surveillance_system_alarm_activator_impl_Port_Type'
       (test));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.event_handlers_alarm_activator;
    --  Return error code
    return Error_Ü;
  end surveillance_system_alarm_Job;

  --  BEGIN: Data types used by all instances of component detector.impl

  type surveillance_system_detector_impl_Integer_Array is
   array (surveillance_system_detector_impl_Port_Type)
     of Standard.Integer;

  type surveillance_system_detector_impl_Port_Kind_Array is
   array (surveillance_system_detector_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Main_surveillance_system_detector_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Main_1_Max_Port_Image_Size);

  type surveillance_system_detector_impl_Port_Image_Array is
   array (surveillance_system_detector_impl_Port_Type)
     of UT_Activity_Main_surveillance_system_detector_impl_Port_Image_Array_Component;

  type surveillance_system_detector_impl_Address_Array is
   array (surveillance_system_detector_impl_Port_Type)
     of System.Address;

  type surveillance_system_detector_impl_Overflow_Protocol_Array is
   array (surveillance_system_detector_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component detector.impl

  surveillance_system_detector1_Port_Kinds : constant surveillance_system_detector_impl_Port_Kind_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.In_Event_Port,
    door =>
     PolyORB_HI.Port_Kinds.In_Event_Port);

  surveillance_system_detector1_Port_Images : constant surveillance_system_detector_impl_Port_Image_Array :=
   (motion =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector1_motion_K),
    door =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector1_door_K));

  surveillance_system_detector1_FIFO_Sizes : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     16,
    door =>
     16);

  surveillance_system_detector1_Offsets : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     1,
    door =>
     17);

  surveillance_system_detector1_Overflow_Protocols : constant surveillance_system_detector_impl_Overflow_Protocol_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    door =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  surveillance_system_detector1_Urgencies : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  surveillance_system_detector1_Total_FIFO_Size : constant Standard.Integer :=
   32;

  surveillance_system_detector1_N_Destinations : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  detector1_Destinations : constant surveillance_system_detector_impl_Address_Array :=
   (motion =>
     System.null_Address,
    door =>
     System.null_Address);

  package surveillance_system_detector1_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => surveillance_system_detector_impl_Port_Type,
      Integer_Array => surveillance_system_detector_impl_Integer_Array,
      Port_Kind_Array => surveillance_system_detector_impl_Port_Kind_Array,
      Port_Image_Array => surveillance_system_detector_impl_Port_Image_Array,
      Address_Array => surveillance_system_detector_impl_Address_Array,
      Overflow_Protocol_Array => surveillance_system_detector_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => surveillance_system_detector_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.main_detector1_K,
      Thread_Port_Kinds => surveillance_system_detector1_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => surveillance_system_detector1_Port_Images,
      Thread_Fifo_Sizes => surveillance_system_detector1_FIFO_Sizes,
      Thread_Fifo_Offsets => surveillance_system_detector1_Offsets,
      Thread_Overflow_Protocols => surveillance_system_detector1_Overflow_Protocols,
      Urgencies => surveillance_system_detector1_Urgencies,
      Global_Data_Queue_Size => surveillance_system_detector1_Total_FIFO_Size,
      N_Destinations => surveillance_system_detector1_N_Destinations,
      Destinations => detector1_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => surveillance_system_detector1_Task.Next_Deadline);

  --  Periodic task : detector1

  ---------------------------------------
  -- surveillance_system_detector1_Job -- 
  ---------------------------------------

  function surveillance_system_detector1_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    --  Dequeue the IN port values
    surveillance_system_detector1_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (motion));
    surveillance_system_detector1_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (door));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.event_handlers_detection_handler;
    --  Return error code
    return Error_Ü;
  end surveillance_system_detector1_Job;

  surveillance_system_detector2_Port_Kinds : constant surveillance_system_detector_impl_Port_Kind_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.In_Event_Port,
    door =>
     PolyORB_HI.Port_Kinds.In_Event_Port);

  surveillance_system_detector2_Port_Images : constant surveillance_system_detector_impl_Port_Image_Array :=
   (motion =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector2_motion_K),
    door =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector2_door_K));

  surveillance_system_detector2_FIFO_Sizes : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     16,
    door =>
     16);

  surveillance_system_detector2_Offsets : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     1,
    door =>
     17);

  surveillance_system_detector2_Overflow_Protocols : constant surveillance_system_detector_impl_Overflow_Protocol_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    door =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  surveillance_system_detector2_Urgencies : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  surveillance_system_detector2_Total_FIFO_Size : constant Standard.Integer :=
   32;

  surveillance_system_detector2_N_Destinations : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  detector2_Destinations : constant surveillance_system_detector_impl_Address_Array :=
   (motion =>
     System.null_Address,
    door =>
     System.null_Address);

  package surveillance_system_detector2_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => surveillance_system_detector_impl_Port_Type,
      Integer_Array => surveillance_system_detector_impl_Integer_Array,
      Port_Kind_Array => surveillance_system_detector_impl_Port_Kind_Array,
      Port_Image_Array => surveillance_system_detector_impl_Port_Image_Array,
      Address_Array => surveillance_system_detector_impl_Address_Array,
      Overflow_Protocol_Array => surveillance_system_detector_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => surveillance_system_detector_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.main_detector2_K,
      Thread_Port_Kinds => surveillance_system_detector2_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => surveillance_system_detector2_Port_Images,
      Thread_Fifo_Sizes => surveillance_system_detector2_FIFO_Sizes,
      Thread_Fifo_Offsets => surveillance_system_detector2_Offsets,
      Thread_Overflow_Protocols => surveillance_system_detector2_Overflow_Protocols,
      Urgencies => surveillance_system_detector2_Urgencies,
      Global_Data_Queue_Size => surveillance_system_detector2_Total_FIFO_Size,
      N_Destinations => surveillance_system_detector2_N_Destinations,
      Destinations => detector2_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => surveillance_system_detector2_Task.Next_Deadline);

  --  Periodic task : detector2

  ---------------------------------------
  -- surveillance_system_detector2_Job -- 
  ---------------------------------------

  function surveillance_system_detector2_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    --  Dequeue the IN port values
    surveillance_system_detector2_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (motion));
    surveillance_system_detector2_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (door));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.event_handlers_detection_handler;
    --  Return error code
    return Error_Ü;
  end surveillance_system_detector2_Job;

  surveillance_system_detector3_Port_Kinds : constant surveillance_system_detector_impl_Port_Kind_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.In_Event_Port,
    door =>
     PolyORB_HI.Port_Kinds.In_Event_Port);

  surveillance_system_detector3_Port_Images : constant surveillance_system_detector_impl_Port_Image_Array :=
   (motion =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector3_motion_K),
    door =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_detector3_door_K));

  surveillance_system_detector3_FIFO_Sizes : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     16,
    door =>
     16);

  surveillance_system_detector3_Offsets : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     1,
    door =>
     17);

  surveillance_system_detector3_Overflow_Protocols : constant surveillance_system_detector_impl_Overflow_Protocol_Array :=
   (motion =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    door =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  surveillance_system_detector3_Urgencies : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  surveillance_system_detector3_Total_FIFO_Size : constant Standard.Integer :=
   32;

  surveillance_system_detector3_N_Destinations : constant surveillance_system_detector_impl_Integer_Array :=
   (motion =>
     0,
    door =>
     0);

  detector3_Destinations : constant surveillance_system_detector_impl_Address_Array :=
   (motion =>
     System.null_Address,
    door =>
     System.null_Address);

  package surveillance_system_detector3_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => surveillance_system_detector_impl_Port_Type,
      Integer_Array => surveillance_system_detector_impl_Integer_Array,
      Port_Kind_Array => surveillance_system_detector_impl_Port_Kind_Array,
      Port_Image_Array => surveillance_system_detector_impl_Port_Image_Array,
      Address_Array => surveillance_system_detector_impl_Address_Array,
      Overflow_Protocol_Array => surveillance_system_detector_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => surveillance_system_detector_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.main_detector3_K,
      Thread_Port_Kinds => surveillance_system_detector3_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => surveillance_system_detector3_Port_Images,
      Thread_Fifo_Sizes => surveillance_system_detector3_FIFO_Sizes,
      Thread_Fifo_Offsets => surveillance_system_detector3_Offsets,
      Thread_Overflow_Protocols => surveillance_system_detector3_Overflow_Protocols,
      Urgencies => surveillance_system_detector3_Urgencies,
      Global_Data_Queue_Size => surveillance_system_detector3_Total_FIFO_Size,
      N_Destinations => surveillance_system_detector3_N_Destinations,
      Destinations => detector3_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => surveillance_system_detector3_Task.Next_Deadline);

  --  Periodic task : detector3

  ---------------------------------------
  -- surveillance_system_detector3_Job -- 
  ---------------------------------------

  function surveillance_system_detector3_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    --  Dequeue the IN port values
    surveillance_system_detector3_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (motion));
    surveillance_system_detector3_Interrogators.Next_Value
     (surveillance_system_detector_impl_Port_Type'
       (door));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.event_handlers_detection_handler;
    --  Return error code
    return Error_Ü;
  end surveillance_system_detector3_Job;

  --  BEGIN: Data types used by all instances of component rfid_thread.impl

  type surveillance_system_rfid_thread_impl_Integer_Array is
   array (surveillance_system_rfid_thread_impl_Port_Type)
     of Standard.Integer;

  type surveillance_system_rfid_thread_impl_Port_Kind_Array is
   array (surveillance_system_rfid_thread_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Main_surveillance_system_rfid_thread_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Main_1_Max_Port_Image_Size);

  type surveillance_system_rfid_thread_impl_Port_Image_Array is
   array (surveillance_system_rfid_thread_impl_Port_Type)
     of UT_Activity_Main_surveillance_system_rfid_thread_impl_Port_Image_Array_Component;

  type surveillance_system_rfid_thread_impl_Address_Array is
   array (surveillance_system_rfid_thread_impl_Port_Type)
     of System.Address;

  type surveillance_system_rfid_thread_impl_Overflow_Protocol_Array is
   array (surveillance_system_rfid_thread_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component rfid_thread.impl

  surveillance_system_rfid_reader_Port_Kinds : constant surveillance_system_rfid_thread_impl_Port_Kind_Array :=
   (rfid_read =>
     PolyORB_HI.Port_Kinds.In_Event_Port,
    door =>
     PolyORB_HI.Port_Kinds.Out_Event_Port,
    motion =>
     PolyORB_HI.Port_Kinds.Out_Event_Port,
    test =>
     PolyORB_HI.Port_Kinds.Out_Event_Data_Port);

  surveillance_system_rfid_reader_Port_Images : constant surveillance_system_rfid_thread_impl_Port_Image_Array :=
   (rfid_read =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_rfid_read_K),
    door =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_door_K),
    motion =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_motion_K),
    test =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_test_K));

  surveillance_system_rfid_reader_FIFO_Sizes : constant surveillance_system_rfid_thread_impl_Integer_Array :=
   (rfid_read =>
     16,
    door =>
     -1,
    motion =>
     -1,
    test =>
     -1);

  surveillance_system_rfid_reader_Offsets : constant surveillance_system_rfid_thread_impl_Integer_Array :=
   (rfid_read =>
     1,
    door =>
     0,
    motion =>
     0,
    test =>
     0);

  surveillance_system_rfid_reader_Overflow_Protocols : constant surveillance_system_rfid_thread_impl_Overflow_Protocol_Array :=
   (rfid_read =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    door =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    motion =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    test =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  surveillance_system_rfid_reader_Urgencies : constant surveillance_system_rfid_thread_impl_Integer_Array :=
   (rfid_read =>
     0,
    door =>
     0,
    motion =>
     0,
    test =>
     0);

  surveillance_system_rfid_reader_Total_FIFO_Size : constant Standard.Integer :=
   16;

  type UT_Activity_Main_rfid_reader_test_Destinations_Array is
   array (Standard.Positive range <>)
     of PolyORB_HI_Generated.Deployment.Port_Type;

  rfid_reader_test_Destinations : constant UT_Activity_Main_rfid_reader_test_Destinations_Array :=
   UT_Activity_Main_rfid_reader_test_Destinations_Array'
     (1 =>
       PolyORB_HI_Generated.Deployment.main_alarm_test_K);

  surveillance_system_rfid_reader_N_Destinations : constant surveillance_system_rfid_thread_impl_Integer_Array :=
   (rfid_read =>
     0,
    door =>
     0,
    motion =>
     0,
    test =>
     1);

  rfid_reader_Destinations : constant surveillance_system_rfid_thread_impl_Address_Array :=
   (rfid_read =>
     System.null_Address,
    door =>
     System.null_Address,
    motion =>
     System.null_Address,
    test =>
     rfid_reader_test_Destinations'Address);

  package surveillance_system_rfid_reader_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => surveillance_system_rfid_thread_impl_Port_Type,
      Integer_Array => surveillance_system_rfid_thread_impl_Integer_Array,
      Port_Kind_Array => surveillance_system_rfid_thread_impl_Port_Kind_Array,
      Port_Image_Array => surveillance_system_rfid_thread_impl_Port_Image_Array,
      Address_Array => surveillance_system_rfid_thread_impl_Address_Array,
      Overflow_Protocol_Array => surveillance_system_rfid_thread_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => surveillance_system_rfid_thread_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.main_rfid_reader_K,
      Thread_Port_Kinds => surveillance_system_rfid_reader_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => surveillance_system_rfid_reader_Port_Images,
      Thread_Fifo_Sizes => surveillance_system_rfid_reader_FIFO_Sizes,
      Thread_Fifo_Offsets => surveillance_system_rfid_reader_Offsets,
      Thread_Overflow_Protocols => surveillance_system_rfid_reader_Overflow_Protocols,
      Urgencies => surveillance_system_rfid_reader_Urgencies,
      Global_Data_Queue_Size => surveillance_system_rfid_reader_Total_FIFO_Size,
      N_Destinations => surveillance_system_rfid_reader_N_Destinations,
      Destinations => rfid_reader_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => surveillance_system_rfid_reader_Task.Next_Deadline);

  --  Periodic task : rfid_reader

  -----------------------------------------
  -- surveillance_system_rfid_reader_Job -- 
  -----------------------------------------

  function surveillance_system_rfid_reader_Job return PolyORB_HI.Errors.Error_Kind is
    detector_handler_Status : PolyORB_HI_Generated.Subprograms.event_handlers_rfid_handler_Status;
    Error_Ü : PolyORB_HI.Errors.Error_Kind;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    --  Dequeue the IN port values
    surveillance_system_rfid_reader_Interrogators.Next_Value
     (surveillance_system_rfid_thread_impl_Port_Type'
       (rfid_read));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.event_handlers_rfid_handler
     (Status => detector_handler_Status);
    if (PolyORB_HI_Generated.Subprograms.Get_Count
     (detector_handler_Status,
      PolyORB_HI_Generated.Subprograms.event_handlers_rfid_handler_Port_Type'
       (PolyORB_HI_Generated.Subprograms.Data_Source))
      >= 1)
    then
      PolyORB_HI_Generated.Activity.Put_Value
       (PolyORB_HI_Generated.Deployment.main_rfid_reader_K,
        PolyORB_HI_Generated.Activity.surveillance_system_rfid_thread_impl_Interface'
         (Port => test,
          test_DATA => PolyORB_HI_Generated.Subprograms.Get_Value
           (detector_handler_Status,
            PolyORB_HI_Generated.Subprograms.event_handlers_rfid_handler_Port_Type'
             (PolyORB_HI_Generated.Subprograms.Data_Source)).Data_Source_DATA));
    end if;
    --  Send the call sequence OUT port values
    Error_Ü :=
     surveillance_system_rfid_reader_Interrogators.Send_Output
       (test);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    --  Return error code
    return Error_Ü;
  end surveillance_system_rfid_reader_Job;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return surveillance_system_alarm_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_alarm_activator_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_alarm_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_alarm_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
   return surveillance_system_alarm_activator_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_alarm_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_alarm_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_alarm_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_alarm_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_alarm_activator_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_alarm_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_alarm_activator_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_alarm_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out surveillance_system_alarm_activator_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_alarm_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return surveillance_system_detector1_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_detector_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_detector1_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_detector1_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
   return surveillance_system_detector_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_detector1_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_detector1_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_detector1_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_detector1_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_detector_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_detector1_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_detector_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_detector1_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out surveillance_system_detector_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_detector1_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return surveillance_system_rfid_reader_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_rfid_thread_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_rfid_reader_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_rfid_reader_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
   return surveillance_system_rfid_thread_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_rfid_reader_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_rfid_reader_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_rfid_reader_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return surveillance_system_rfid_reader_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : surveillance_system_rfid_thread_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_rfid_reader_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : surveillance_system_rfid_thread_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_rfid_reader_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out surveillance_system_rfid_thread_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    surveillance_system_rfid_reader_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

end PolyORB_HI_Generated.Activity;
