--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package body PolyORB_HI_Generated.Subprograms is

  ------------------------------------
  -- event_handlers_alarm_activator -- 
  ------------------------------------

  procedure event_handlers_alarm_activator is
    Nyi : exception;
  begin
    raise Nyi;
  end event_handlers_alarm_activator;

  --------------------------------------
  -- event_handlers_detection_handler -- 
  --------------------------------------

  procedure event_handlers_detection_handler is
    Nyi : exception;
  begin
    raise Nyi;
  end event_handlers_detection_handler;

  ---------------------------------
  -- event_handlers_rfid_handler -- 
  ---------------------------------

  procedure event_handlers_rfid_handler is
    Nyi : exception;
  begin
    raise Nyi;
  end event_handlers_rfid_handler;

end PolyORB_HI_Generated.Subprograms;
