--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with PolyORB_HI.Periodic_Task;
pragma Elaborate_All (PolyORB_HI.Periodic_Task);

package PolyORB_HI_Generated.Job is

  --  Periodic task : alarm

  procedure surveillance_system_alarm_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_alarm_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.main_alarm_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => 70,
      Task_Stack_Size => 100000,
      Job => surveillance_system_alarm_Job);

  --  Periodic task : detector1

  procedure surveillance_system_detector1_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_detector1_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.main_detector1_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => 90,
      Task_Stack_Size => 100000,
      Job => surveillance_system_detector1_Job);

  --  Periodic task : detector2

  procedure surveillance_system_detector2_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_detector2_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.main_detector2_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => 89,
      Task_Stack_Size => 100000,
      Job => surveillance_system_detector2_Job);

  --  Periodic task : detector3

  procedure surveillance_system_detector3_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_detector3_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.main_detector3_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => 88,
      Task_Stack_Size => 100000,
      Job => surveillance_system_detector3_Job);

  --  Periodic task : rfid_reader

  procedure surveillance_system_rfid_reader_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package surveillance_system_rfid_reader_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.main_rfid_reader_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => 91,
      Task_Stack_Size => 100000,
      Job => surveillance_system_rfid_reader_Job);

end PolyORB_HI_Generated.Job;
